title: Nollstead Studio
description: Portfolio and project showcase by Craig Sweet.
remote_theme: just-the-docs/just-the-docs-template
#logo: # optional, you can add later

plugins:
  - jekyll-remote-theme
  
permalink: pretty

# Force Jekyll to publish JSON files anywhere in the repo
include:
  - "*.json"
  - "**/*.json"

# Projects collection (each file in _projects/ becomes a page)
collections:
  projects:
    output: true

# Make each project URL live at /project-slug/ (e.g., /project2/)
defaults:
  - scope:
      path: ""
      type: projects
    values:
      permalink: "/:title/"


just_the_docs:
  color_scheme: light
  search_enabled: true

# permalink: "/:path/:title/"
